source("./parse_labyrinth.m")
source("./get_adjacency_matrix.m")
source("./get_link_matrix.m")
source("./get_Jacobi_parameters.m")
source("./perform_iterative.m")
source("./heuristic_greedy.m")
source("./decode_path.m")
